const books = [
  {
    id: 14,
    name: "Tuổi Trẻ Đáng Giá Bao Nhiêu",
    author: "Rosie Nguyễn",
    writtenYear: 2016,
    publishDate: "10-03-2016",
    description: "Truyền cảm hứng cho người trẻ sống hết mình.",
    price: 130000,
    discount: 0,
    category: "Tâm lý - Kỹ năng sống",
    image: "images/Tuổi Trẻ Đáng Giá Bao Nhiêu.jpg",
    best: false
  },
  {
    id: 7,
    name: "Node.js Design Patterns",
    author: "Mario Casciaro & Luciano Mammino",
    writtenYear: 2020,
    publishDate: "20-07-2020",
    description: "Hướng dẫn chuyên sâu về kiến trúc, các mẫu thiết kế (Design Patterns) và thực hành tốt nhất để xây dựng ứng dụng Node.js quy mô lớn.",
    price: 850000,
    discount: 15,
    category: "Lập trình",
    image: "images/Node.js Design Patterns.jpg",
    best: true
  },
  {
    id: 33,
    name: "Truyện Kiều",
    author: "Nguyễn Du",
    writtenYear: 1820,
    publishDate: "01-01-1820",
    description: "Tác phẩm văn học kinh điển của Việt Nam.",
    price: 120000,
    discount: 0,
    category: "Văn học",
    image: "images/Truyện Kiều.jpg",
    best: true
  },
  {
    id: 1,
    name: "Clean Code",
    author: "Robert C. Martin",
    writtenYear: 2008,
    publishDate: "01-08-2008",
    description: "Cuốn sách kinh điển về cách viết code sạch và chuyên nghiệp.",
    price: 220000,
    discount: 10,
    category: "Lập trình",
    image: "images/Clean Code.jpg",
    best: true
  },
  {
    id: 29,
    name: "Hooked: Bị Bỏ Bùa",
    author: "Nir Eyal",
    writtenYear: 2014,
    publishDate: "04-11-2014",
    description: "Khám phá mô hình 4 bước để tạo ra những sản phẩm khiến người dùng không thể rời mắt.",
    price: 145000,
    discount: 15,
    category: "Sản phẩm - Tâm lý",
    image: "images/Nir Eyal.png",
    best: true
  },
  {
    id: 42,
    name: "Harry Potter Và Hòn Đá Phù Thủy",
    author: "J.K. Rowling",
    writtenYear: 1997,
    publishDate: "26-06-1997",
    description: "Phần đầu của loạt truyện Harry Potter.",
    price: 220000,
    discount: 10,
    category: "Thiếu nhi",
    image: "images/Harry Potter Và Hòn Đá Phù Thủy.jpg",
    best: true
  },
  {
    id: 20,
    name: "Tâm Lý Học Về Tiền",
    author: "Morgan Housel",
    writtenYear: 2020,
    publishDate: "08-09-2020",
    description: "Khám phá cách những thành kiến và cái tôi ảnh hưởng đến các quyết định tài chính của chúng ta.",
    price: 189000,
    discount: 20,
    category: "Kinh doanh - Tâm lý",
    image: "images/Tâm Lý Học Về Tiền.jpg",
    best: true
  },
  {
    id: 8,
    name: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    writtenYear: 1994,
    publishDate: "21-10-1994",
    description: "Cuốn sách đặt nền móng cho 23 mẫu thiết kế phần mềm kinh điển trong lập trình hướng đối tượng.",
    price: 320000,
    discount: 5,
    category: "Lập trình",
    image: "images/sach08.jpg",
    best: true
  },
  {
    id: 38,
    name: "Những Người Khốn Khổ",
    author: "Victor Hugo",
    writtenYear: 1862,
    publishDate: "01-01-1862",
    description: "Tiểu thuyết kinh điển của văn học Pháp.",
    price: 240000,
    discount: 10,
    category: "Văn học",
    image: "images/Những Người Khốn Khổ.jpg",
    best: true
  },
  {
    id: 25,
    name: "Zero to One (Từ Không Đến Một)",
    author: "Peter Thiel & Blake Masters",
    writtenYear: 2014,
    publishDate: "16-09-2014",
    description: "Ghi chép về khởi nghiệp và cách xây dựng tương lai thông qua những ý tưởng độc bản.",
    price: 155000,
    discount: 15,
    category: "Kinh doanh - Khởi nghiệp",
    image: "images/Zero to One.jpg",
    best: true
  },
  {
    id: 6,
    name: "React JS Toàn Tập",
    author: "Dan Abramov",
    writtenYear: 2018,
    publishDate: "15-07-2018",
    description: "Học React từ cơ bản đến chuyên sâu.",
    price: 230000,
    discount: 20,
    category: "Lập trình",
    image: "images/React JS Toàn Tập.jpg",
    best: true
  },
  {
    id: 32,
    name: "Essentialism (Chủ Nghĩa Tối Giản)",
    author: "Greg McKeown",
    writtenYear: 2014,
    publishDate: "15-04-2014",
    description: "Kỷ luật theo đuổi sự ít ỏi để đạt được hiệu quả tối đa trong công việc và cuộc sống.",
    price: 160000,
    discount: 10,
    category: "Kỹ năng sống - Quản lý thời gian",
    image: "images/Essentialism.png",
    best: true
  },
  {
    id: 28,
    name: "Contagious: Hiệu Ứng Lan Truyền",
    author: "Jonah Berger",
    writtenYear: 2013,
    publishDate: "05-03-2013",
    description: "Khám phá 6 yếu tố tâm lý khiến một ý tưởng hoặc sản phẩm trở nên phổ biến và lan tỏa mạnh mẽ.",
    price: 165000,
    discount: 10,
    category: "Marketing - Truyền thông",
    image: "images/Contagious.jpg",
    best: true
  },
  {
    id: 31,
    name: "Phi Lý Trí (Predictably Irrational)",
    author: "Dan Ariely",
    writtenYear: 2008,
    publishDate: "19-02-2008",
    description: "Khám phá những động lực vô hình đằng sau các quyết định sai lầm của con người.",
    price: 159000,
    discount: 10,
    category: "Tâm lý - Kinh tế",
    image: "images/Phi Lý Trí.jpg",
    best: true
  },
  {
    id: 9,
    name: "Đắc Nhân Tâm",
    author: "Dale Carnegie",
    writtenYear: 1936,
    publishDate: "01-01-1936",
    description: "Cuốn sách nổi tiếng về nghệ thuật giao tiếp và ứng xử.",
    price: 150000,
    discount: 5,
    category: "Tâm lý - Kỹ năng sống",
    image: "images/Đắc Nhân Tâm.jpg",
    best: true
  },
  {
    id: 41,
    name: "Dế Mèn Phiêu Lưu Ký",
    author: "Tô Hoài",
    writtenYear: 1941,
    publishDate: "01-01-1941",
    description: "Tác phẩm thiếu nhi nổi tiếng Việt Nam.",
    price: 95000,
    discount: 0,
    category: "Thiếu nhi",
    image: "images/Dế Mèn Phiêu Lưu Ký.jpg",
    best: true
  },
  {
    id: 17,
    name: "Cha Giàu Cha Nghèo",
    author: "Robert T. Kiyosaki",
    writtenYear: 1997,
    publishDate: "01-04-1997",
    description: "Bài học tài chính cá nhân nổi tiếng toàn cầu.",
    price: 190000,
    discount: 10,
    category: "Kinh doanh",
    image: "images/Cha Giàu Cha Nghèo.jpg",
    best: true
  },
  {
    id: 2,
    name: "The Pragmatic Programmer",
    author: "Andrew Hunt",
    writtenYear: 1999,
    publishDate: "30-10-1999",
    description: "Hướng dẫn tư duy và kỹ năng lập trình chuyên nghiệp.",
    price: 250000,
    discount: 15,
    category: "Lập trình",
    image: "images/The Pragmatic Programmer.jpg",
    best: true
  },
  {
    id: 40,
    name: "Nhà Giả Kim",
    author: "Paulo Coelho",
    writtenYear: 1988,
    publishDate: "01-01-1988",
    description: "Hành trình theo đuổi ước mơ.",
    price: 150000,
    discount: 0,
    category: "Văn học",
    image: "images/Nhà Giả Kim.jpg",
    best: false
  },
  {
    id: 11,
    name: "Tư Duy Nhanh Và Chậm",
    author: "Daniel Kahneman",
    writtenYear: 2011,
    publishDate: "25-10-2011",
    description: "Giải thích cách con người suy nghĩ và ra quyết định.",
    price: 210000,
    discount: 10,
    category: "Tâm lý - Kỹ năng sống",
    image: "images/Tư Duy Nhanh Và Chậm.jpg",
    best: false
  },
  {
    id: 3,
    name: "JavaScript Nâng Cao",
    author: "Kyle Simpson",
    writtenYear: 2015,
    publishDate: "12-05-2015",
    description: "Hiểu sâu về JavaScript và cơ chế hoạt động bên trong.",
    price: 195000,
    discount: 5,
    category: "Lập trình",
    image: "images/JavaScript Nâng Cao.jpg",
    best: false
  },
  {
    id: 36,
    name: "Số Đỏ",
    author: "Vũ Trọng Phụng",
    writtenYear: 1936,
    publishDate: "01-01-1936",
    description: "Tác phẩm trào phúng nổi tiếng.",
    price: 130000,
    discount: 10,
    category: "Văn học",
    image: "images/Số Đỏ.jpg",
    best: false
  },
  {
    id: 22,
    name: "Khởi Nghiệp Tinh Gọn",
    author: "Eric Ries",
    writtenYear: 2011,
    publishDate: "13-09-2011",
    description: "Phương pháp khởi nghiệp hiện đại.",
    price: 210000,
    discount: 5,
    category: "Kinh doanh",
    image: "images/Khởi Nghiệp Tinh Gọn.jpg",
    best: false
  },
  {
    id: 47,
    name: "Nhật Ký Chú Bé Nhút Nhát",
    author: "Jeff Kinney",
    writtenYear: 2007,
    publishDate: "01-01-2007",
    description: "Những câu chuyện hài hước tuổi học trò.",
    price: 155000,
    discount: 0,
    category: "Thiếu nhi",
    image: "images/Nhật Ký Chú Bé Nhút Nhát.jpg",
    best: false
  },
  {
    id: 15,
    name: "Dám Bị Ghét",
    author: "Ichiro Kishimi",
    writtenYear: 2013,
    publishDate: "01-12-2013",
    description: "Triết lý sống hạnh phúc theo tâm lý học Adler.",
    price: 165000,
    discount: 5,
    category: "Tâm lý - Kỹ năng sống",
    image: "images/Dám Bị Ghét.jpg",
    best: false
  },
  {
    id: 39,
    name: "Ông Già Và Biển Cả",
    author: "Ernest Hemingway",
    writtenYear: 1952,
    publishDate: "01-01-1952",
    description: "Tác phẩm đoạt giải Nobel Văn học.",
    price: 180000,
    discount: 5,
    category: "Văn học",
    image: "images/Ông Già Và Biển Cả.jpg",
    best: false
  },
  {
    id: 4,
    name: "Python Cơ Bản",
    author: "Mark Lutz",
    writtenYear: 2013,
    publishDate: "01-06-2013",
    description: "Hướng dẫn học Python từ cơ bản đến nâng cao.",
    price: 210000,
    discount: 0,
    category: "Lập trình",
    image: "images/Python Cơ Bản.jpg",
    best: false
  },
  {
    id: 10,
    name: "7 Thói Quen Hiệu Quả",
    author: "Stephen R. Covey",
    writtenYear: 1989,
    publishDate: "15-08-1989",
    description: "Hướng dẫn xây dựng thói quen để thành công.",
    price: 180000,
    discount: 0,
    category: "Tâm lý - Kỹ năng sống",
    image: "images/7 Thói Quen Hiệu Quả.jpg",
    best: true
  },
  {
    id: 26,
    name: "Tiếp Thị 4.0",
    author: "Philip Kotler",
    writtenYear: 2017,
    publishDate: "01-01-2017",
    description: "Marketing trong thời đại kỹ thuật số.",
    price: 210000,
    discount: 5,
    category: "Marketing",
    image: "images/Tiếp Thị 4.0.jpg",
    best: false
  },
  {
    id: 44,
    name: "Không Gia Đình",
    author: "Hector Malot",
    writtenYear: 1878,
    publishDate: "01-01-1878",
    description: "Hành trình đầy cảm động của cậu bé Rémi.",
    price: 170000,
    discount: 0,
    category: "Thiếu nhi",
    image: "images/Không Gia Đình.jpg",
    best: false
  },
  {
    id: 34,
    name: "Tắt Đèn",
    author: "Ngô Tất Tố",
    writtenYear: 1939,
    publishDate: "01-01-1939",
    description: "Phản ánh xã hội Việt Nam thời phong kiến.",
    price: 110000,
    discount: 5,
    category: "Văn học",
    image: "images/Tắt Đèn.jpg",
    best: false
  },
  {
    id: 18,
    name: "Nghĩ Giàu Làm Giàu",
    author: "Napoleon Hill",
    writtenYear: 1937,
    publishDate: "01-01-1937",
    description: "Tư duy làm giàu kinh điển mọi thời đại.",
    price: 175000,
    discount: 5,
    category: "Kinh doanh",
    image: "images/Nghĩ Giàu Làm Giàu.jpg",
    best: false
  },
  {
    id: 48,
    name: "Cuộc Phiêu Lưu Của Tom Sawyer",
    author: "Mark Twain",
    writtenYear: 1876,
    publishDate: "01-01-1876",
    description: "Tác phẩm thiếu nhi kinh điển.",
    price: 175000,
    discount: 5,
    category: "Thiếu nhi",
    image: "images/Cuộc Phiêu Lưu Của Tom Sawyer.jpg",
    best: false
  },
  {
    id: 12,
    name: "Quẳng Gánh Lo Đi Và Vui Sống",
    author: "Dale Carnegie",
    writtenYear: 1948,
    publishDate: "01-01-1948",
    description: "Cách vượt qua lo lắng và sống tích cực hơn.",
    price: 160000,
    discount: 10,
    category: "Tâm lý - Kỹ năng sống",
    image: "images/Quẳng Gánh Lo Đi Và Vui Sống.jpg",
    best: false
  },
  {
    id: 21,
    name: "Từ Tốt Đến Vĩ Đại",
    author: "Jim Collins",
    writtenYear: 2001,
    publishDate: "01-01-2001",
    description: "Phân tích các công ty vĩ đại trên thế giới.",
    price: 220000,
    discount: 10,
    category: "Kinh doanh",
    image: "images/Từ Tốt Đến Vĩ Đại.jpg",
    best: false
  },
  {
    id: 43,
    name: "Hoàng Tử Bé",
    author: "Antoine de Saint-Exupéry",
    writtenYear: 1943,
    publishDate: "01-01-1943",
    description: "Câu chuyện giàu ý nghĩa cho mọi lứa tuổi.",
    price: 140000,
    discount: 5,
    category: "Thiếu nhi",
    image: "images/Hoàng Tử Bé.jpg",
    best: false
  },
  {
    id: 30,
    name: "Branding 4.0",
    author: "Hermawan Kartajaya",
    writtenYear: 2018,
    publishDate: "01-01-2018",
    description: "Xây dựng thương hiệu thời đại số.",
    price: 215000,
    discount: 5,
    category: "Marketing",
    image: "images/Branding 4.0.jpg",
    best: false
  },
  {
    id: 45,
    name: "Charlie Và Nhà Máy Sô Cô La",
    author: "Roald Dahl",
    writtenYear: 1964,
    publishDate: "01-01-1964",
    description: "Câu chuyện thú vị về cậu bé Charlie.",
    price: 160000,
    discount: 5,
    category: "Thiếu nhi",
    image: "images/Charlie Và Nhà Máy Sô Cô La.jpg",
    best: false
  },
  {
    id: 5,
    name: "C++ Thực Hành",
    author: "Bjarne Stroustrup",
    writtenYear: 2014,
    publishDate: "10-09-2014",
    description: "Học C++ qua các ví dụ thực tế.",
    price: 185000,
    discount: 10,
    category: "Lập trình",
    image: "images/C++ Thực Hành.jpg",
    best: false
  },
  {
    id: 37,
    name: "Lão Hạc",
    author: "Nam Cao",
    writtenYear: 1943,
    publishDate: "01-01-1943",
    description: "Câu chuyện cảm động về tình phụ tử.",
    price: 105000,
    discount: 0,
    category: "Văn học",
    image: "images/Lão Hạc.jpg",
    best: false
  },
  {
    id: 24,
    name: "Đừng Bao Giờ Đi Ăn Một Mình",
    author: "Keith Ferrazzi",
    writtenYear: 2005,
    publishDate: "01-01-2005",
    description: "Nghệ thuật xây dựng mối quan hệ trong kinh doanh.",
    price: 185000,
    discount: 5,
    category: "Kinh doanh",
    image: "images/Đừng Bao Giờ Đi Ăn Một Mình.jpg",
    best: false
  },
  {
    id: 13,
    name: "Sức Mạnh Tiềm Thức",
    author: "Joseph Murphy",
    writtenYear: 1963,
    publishDate: "01-01-1963",
    description: "Khám phá sức mạnh tiềm thức.",
    price: 175000,
    discount: 15,
    category: "Tâm lý - Kỹ năng sống",
    image: "images/Sức Mạnh Tiềm Thức.jpg",
    best: false
  },
  {
    id: 35,
    name: "Chí Phèo",
    author: "Nam Cao",
    writtenYear: 1941,
    publishDate: "01-01-1941",
    description: "Bi kịch của người nông dân trong xã hội cũ.",
    price: 115000,
    discount: 0,
    category: "Văn học",
    image: "images/Chí Phèo.jpg",
    best: false
  },
  {
    id: 27,
    name: "Content Marketing Trong Kỷ Nguyên 4.0",
    author: "Joe Pulizzi",
    writtenYear: 2018,
    publishDate: "01-01-2018",
    description: "Chiến lược nội dung thu hút khách hàng.",
    price: 195000,
    discount: 5,
    category: "Marketing",
    image: "images/Content Marketing Trong Kỷ Nguyên 4.0.jpg",
    best: false
  },
  {
    id: 16,
    name: "Đi Tìm Lẽ Sống",
    author: "Viktor E. Frankl",
    writtenYear: 1946,
    publishDate: "01-01-1946",
    description: "Tìm ý nghĩa cuộc sống trong nghịch cảnh.",
    price: 170000,
    discount: 5,
    category: "Tâm lý - Kỹ năng sống",
    image: "images/Đi Tìm Lẽ Sống.jpg",
    best: false
  },
  {
    id: 19,
    name: "Bí Mật Tư Duy Triệu Phú",
    author: "T. Harv Eker",
    writtenYear: 2005,
    publishDate: "01-01-2005",
    description: "Khám phá tư duy của người giàu.",
    price: 165000,
    discount: 10,
    category: "Kinh doanh",
    image: "images/Bí Mật Tư Duy Triệu Phú.jpg",
    best: false
  },
  {
    id: 46,
    name: "Anne Tóc Đỏ Dưới Chái Nhà Xanh",
    author: "L.M. Montgomery",
    writtenYear: 1908,
    publishDate: "01-01-1908",
    description: "Tuổi thơ đáng yêu của cô bé Anne.",
    price: 185000,
    discount: 10,
    category: "Thiếu nhi",
    image: "images/Anne Tóc Đỏ Dưới Chái Nhà Xanh.jpg",
    best: false
  },
  {
    id: 23,
    name: "Zero To One",
    author: "Peter Thiel",
    writtenYear: 2014,
    publishDate: "16-09-2014",
    description: "Xây dựng startup tạo đột phá.",
    price: 195000,
    discount: 0,
    category: "Kinh doanh",
    image: "images/Zero To One.jpg",
    best: false
  }
];